### ISSUE TITLE
Crash c2-12828 when number of folders exceeds about 17-18

### ISSUE THREAD

**Issue by rutdarkronin** [LioMajor/MaiDumpToolEN#4]
So, as title says, tool just crashes when you have more than 17 or so games either in mai directory or installed. If you try to install something or change loading type - it crashes...

**Comment by rutdarkronin** [comment]
Tested on 3.60-R9 Vita TV with 250GB HDD mounted as ux0: (Thanks Fl0w!).

**Comment by rutdarkronin** [comment]
After that, every game installed with Mai refuses to work with the same error!

**Comment by ShootTheCore** [comment]
I see this is closed but I found a decent workaround for this. Posted it to reddit: https://www.reddit.com/r/VitaPiracy/comments/6zs2lz/semipermanent_solution_to_maidump_crashes_when/
